Inventory/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from register import views as v


urlpatterns = [
    path('admin/', admin.site.urls),
    path("register/", v.register, name="register"),
	path('', v.loginPage, name="login"),  
    path('logout/', v.logoutUser, name="logout"),
    path('performance/', include('products.urls', namespace="products")),
    path('upload/', include('csvs.urls', namespace="csvs")),
    path('customers/', include('customers.urls', namespace="customer")),
    path('goods/', include('goods.urls', namespace="goods"))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

csvs/urls.py
from django.urls import path
from .views import upload_file_view, upload_product_file_view

app_name = 'csvs'

urlpatterns = [
    path('purchase/', upload_file_view, name='upload_view_url'),
    path('product/', upload_product_file_view, name='upload_view_product_url'),
]

products/urls.py
from django.urls import path
from .views import * 

app_name = 'products'

urlpatterns = [
    path('', chart_select_view, name='main-products-view'),
    path('add/',add_purchase_view, name='add-purchase-view'),
    #path('sales/',sales_dist_view, name='sales-view'),    
    path('items/',items_list,name='items_list_url'),
    path('demand/',demand_list,name='demand_list_url'),
    path('calculations/',calculations,name='calculations_url'),
    #path('demand/create/',DemandCreate,name='demand_create_url'),
    path('item/create/',ItemCreate,name='item_create_url'),
    path('delete_items/<str:pk>/', delete_items, name="delete_items"),
    path('update_item/<str:pk>/',update_items,name="update_item"),  
]

products/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from django.core.exceptions import ValidationError
from django.utils.translation import gettext_lazy as _
import math
import scipy.stats as st

# validation

def validate_even(value):
    if value > 100 or value == 0:
        raise ValidationError(
            _('%(value)s is not in between 0 and 100 percent'),
            params={'value': value},
        )
def validate_zero(value):
    if value == 0:
        raise ValidationError(
            _('%(value)s cant be zero'),
            params={'value': value},
        )

# Create your models here.

class Product(models.Model):
    user                 = models.ForeignKey(User, on_delete=models.CASCADE, null=True, related_name="items")
    name                 = models.CharField(max_length=220)
    date                 = models.DateTimeField(auto_now_add=True)
    lead_time            = models.PositiveIntegerField(default='0',blank=True,null=True,validators=[validate_zero])
    service_level        = models.PositiveIntegerField(default='90',blank=True,null=True,validators=[validate_even])
    standard_deviation   = models.DecimalField(default='5', max_digits=6, decimal_places=3, blank=True,null=True)
    carrying_cost        = models.PositiveIntegerField(default='12',blank=False,validators=[validate_even],help_text='Enter as percentage of unit cost')
    ordering_cost        = models.PositiveIntegerField(default='0',blank=False,null=True)
    unit_costprice       = models.PositiveIntegerField(default='0',blank=False,null=True,validators=[validate_zero])
    average_daily_demand = models.DecimalField(default='0',max_digits=10, decimal_places=3, blank=False,null=True)
    total_inventory      = models.IntegerField(default='0',blank=True,null=True)
    eoq                  = models.IntegerField(default='0',blank=True,null=True)
    no_of_workingdays    = models.IntegerField(default='300',blank=True,null=True)
    rq                   = models.IntegerField(default='0',blank=True,null=True)
    z                    = models.DecimalField(max_digits=4,decimal_places=3,default='0',blank=True,null=True)

    def __str__(self):
        return '{} => {}'.format(self.user, self.name)
    
    def save(self, *args, **kwargs):
        self.name = self.name.upper()
        a = 2*float(self.no_of_workingdays)*float(self.average_daily_demand)*float(self.ordering_cost)
        b = float(self.unit_costprice)*float(self.carrying_cost)/100
        self.eoq  = math.sqrt(a/b)
        self.z    = (st.norm.ppf(self.service_level/100))
        self.rq   = float(self.lead_time)*float(self.average_daily_demand)+float(self.z)*float(self.standard_deviation)*float(self.lead_time)
        return super().save(*args, **kwargs)

class Purchase(models.Model):
    user        = models.ForeignKey(User, on_delete=models.CASCADE, null=True,related_name="demand")
    product     = models.ForeignKey(Product, on_delete=models.CASCADE, related_name="demands")
    price       = models.PositiveIntegerField(blank=False,null=True)
    quantity    = models.IntegerField(blank=False,null=True)
    total_price = models.PositiveIntegerField(blank=True)
    date        = models.DateTimeField(default=timezone.now, editable=True)    
    recieved    = models.IntegerField(default='0',blank=False,null=True)


    def save(self, *args, **kwargs):
        self.total_price = self.quantity * self.price
        super().save(*args, **kwargs)

    def __str__(self):
        return "{} sold at {} each".format(self.product, self.price)

products/forms.py
from django import forms
from .models import Purchase, Product
from os import name
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from django.db.models import fields
from django.http import request


class PurchaseForm(forms.ModelForm):
    class Meta:
        model  = Purchase
        fields = ['product', 'quantity', 'price', 'recieved', 'date']

    def __init__(self,user=None,*args,**kwargs):
        super(PurchaseForm,self).__init__(*args,**kwargs)
        if user:
            self.fields['product'].queryset=Product.objects.filter(user=user)

class ItemsForm(forms.ModelForm):
    class Meta:
        model  = Product
        fields = ['name','average_daily_demand','unit_costprice','carrying_cost','ordering_cost','total_inventory','lead_time','service_level','standard_deviation','no_of_workingdays']

    def clean_name(self):
        name = self.cleaned_data.get('name').upper()
        return name

class ItemSearchForm(forms.ModelForm):
   class Meta:
        model = Product
        fields = ['name']

class select_item(forms.ModelForm):
    class Meta:
        model  = Purchase
        fields = ['product']
        

    def __init__(self,user=None,*args,**kwargs):
        super(select_item,self).__init__(*args,**kwargs)
        if user:
            self.fields['product'].queryset=Product.objects.filter(user=user)

products/views.py
from django.shortcuts import get_object_or_404, render, redirect, reverse
from django.contrib import messages 
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.db.models.aggregates import Avg, StdDev,Sum,Variance
from django.db.models.expressions import F
from django.views.generic import TemplateView, View 
from django.core.exceptions import ObjectDoesNotExist, ValidationError
from django.http import HttpResponse
from django.core.paginator import Paginator, EmptyPage,PageNotAnInteger
from numpy.core.fromnumeric import product
from .models import Product, Purchase
from .utils import *
from .forms import *
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import math

# Create your views here.

@login_required(login_url='login')
def chart_select_view(request):
    error_message = None
    df = None
    graph = None
    Quantity = None

    product_df  = pd.DataFrame(Product.objects.all().values().filter(user=request.user))
    purchase_df = pd.DataFrame(Purchase.objects.all().values().filter(user=request.user))
    
    items = Product.objects.all().filter(user=request.user)

    if product_df.shape[0]>0 :
        product_df['product_id'] = product_df['id']
    
    if purchase_df.shape[0]>0 :
        df = pd.merge(purchase_df, product_df, on='product_id').drop(['id_y', 'date_y'], axis=1).rename({'id_x':'id', 'date_x':'date'}, axis=1)
        if request.method == 'POST':
            chart_type = request.POST.get('plot')
            date_from  = request.POST.get('date_from') 
            date_to    = request.POST.get('date_to') 
            item       = request.POST.get('item')
            
            df['date'] = df['date'].apply(lambda x: x.strftime('%Y-%m-%d'))
            df2        = df.groupby(['date','name'], as_index=False)['quantity'].agg('sum')
            df2        = df2[df2["name"].isin([item])]
            Quantity = df2['quantity']   
            
            if chart_type!="":
                if item!="":
                    if date_from!="" and date_to!="":
                        df  = df[(df['date']>date_from)&(df['date']<date_to)]
                        df2 = df.groupby(['date','name'], as_index=False)['quantity'].agg('sum')
                        df2 = df2[df2["name"].isin([item])]
                    # function to get a graph
                    graph = get_simple_plot(chart_type, x=df2['date'], y=df2['quantity'] ,data=df)
                else:
                    error_message = 'please enter an item to continue'
            else:
                error_message = 'please select a chart to continue'

    else:
        error_message = 'no records in database'
        
    context ={
        'error_message': error_message,
        'graph' : graph,
        'Quantity' : Quantity,
        'items' : items,
        #'products' : product_df.to_html(),
        #'purchase' : purchase_df.to_html(),
    }
    return render(request, 'products/main.html', context)

@login_required(login_url='login')
def add_purchase_view(request):
        form=PurchaseForm(request.user)
        if request.method == 'POST':
            form=PurchaseForm(request.user,request.POST) 
            if form.is_valid():
                n = form.cleaned_data["product"]
                l = form.cleaned_data["quantity"]
                c = form.cleaned_data["price"]
                o = form.cleaned_data["recieved"] 
                d = form.cleaned_data["date"]

                reporter = request.user.items.get(name=n, user=request.user)
                reporter.total_inventory = F('total_inventory')-l+o
                reporter.save()
                t = Purchase(product=n,quantity=l,price=c,recieved=o,date=d)
                t.save()
                request.user.demand.add(t)
                
                return redirect('products:add-purchase-view')
                    
        return render(request,'products/add.html',context={'form':PurchaseForm(request.user) })

@login_required(login_url='login')
def items_list(request):
    ite   = None
    total = None

    try:
        ite = request.user.items.all()
        #ite = Product.objects.all()
    except ObjectDoesNotExist:
        messages.info(request,"There are no items.....")
    form = ItemSearchForm(request.POST or None)

    if request.method == 'POST':
            try:
                ite = request.user.items.filter(name__icontains=form['name'].value())
            except ObjectDoesNotExist:
                messages.info(request,"There are no items.....")
    
    context = {
        "form": form,
        "items":ite,
        "total":total
    }
    return render(request,'products/items_list.html',context)

@login_required(login_url='login')
def demand_list(request,*args,**kwargs):
    itee=None
    
    try:
        itee=request.user.demand.all()
        paginator = Paginator(itee, 30) # 3 posts in each page
        page = request.GET.get('page')
        try:
            posts = paginator.page(page)
        except PageNotAnInteger:
            # If page is not an integer deliver the first page
            posts = paginator.page(1)
        except EmptyPage:
            # If page is out of range deliver last page of results
            posts = paginator.page(paginator.num_pages)
    except ObjectDoesNotExist:
        messages.info(request,"No purchases has been recorded.....")

    return render(request,'products/demand_list.html',context={'page': page, 'posts': posts})

@login_required(login_url='login')
def ItemCreate(request):
        form = ItemsForm()
        if request.method == 'POST':
            form=ItemsForm(request.POST) 
            if form.is_valid():
                n = form.cleaned_data["name"]
                l = form.cleaned_data["lead_time"]
                c = form.cleaned_data["carrying_cost"]
                o = form.cleaned_data["ordering_cost"]
                t = form.cleaned_data["total_inventory"]
                u = form.cleaned_data["unit_costprice"]
                s = form.cleaned_data["service_level"]
                w = form.cleaned_data["no_of_workingdays"]
                d = form.cleaned_data["standard_deviation"]
                a = form.cleaned_data["average_daily_demand"]

                for i in request.user.items.all():
                    if i.name==n:
                        messages.error(request, n +' Item Already Created')
                        return redirect('products:item_create_url')
              
                t = Product(name=n,lead_time=l,average_daily_demand=a,carrying_cost=c,ordering_cost=o,total_inventory=t,unit_costprice=u,service_level=s,no_of_workingdays=w,standard_deviation=d)
                t.save()
                request.user.items.add(t) 
                messages.success(request, n +' Item Created')
                return redirect('products:items_list_url')
                    
        return render(request,'products/item_create.html',context={'form':form, 'product_message':None })

@login_required(login_url='login')
def delete_items(request,pk):
    query_set = Product.objects.get(id=pk)
    
    if request.method =='POST':
        query_set.delete()
        messages.success(request,query_set.name + ' Removed')
        return redirect('products:items_list_url')
     
    context={
        'item':query_set.name
        }
    return render(request,'products/delete_items.html',context)

@login_required(login_url='login')
def update_items(request,pk):
    query_set = Product.objects.get(id=pk)
    form      = ItemsForm(instance=query_set)
    n         = query_set.name
    
    if request.method=='POST':
        form = ItemsForm(request.POST,instance=query_set)
        if form.is_valid():
            form.save()
            messages.info(request, n + '  Updated to ' + query_set.name)
            return redirect('products:items_list_url')
    
    context={
        'form':form
    }
    return render(request,'products/update_item.html',context)

@login_required(login_url='login')
def calculations(request):
    item_df   = pd.DataFrame(Product.objects.all().values().filter(user=request.user))
    demand_df = pd.DataFrame(Purchase.objects.all().values().filter(user=request.user))
    error = None
    
    if demand_df.shape[0]>0:
        item_df.rename(columns = {'id':'product_id'}, inplace = True)
        df = pd.merge(item_df,demand_df,on='product_id')
        df['date_y'] = pd.to_datetime(df['date_y'], format='%y-%m-%d')
        df = df.groupby(['date_y','name'], as_index=False).aggregate({'quantity':'sum', 'total_price':'sum'})
        
        df.rename(columns = {'name':'Item Name'}, inplace = True)
        df['Year/Month'] = df['date_y'].dt.strftime('%Y/%m')
        df = df.groupby(['Year/Month','Item Name']).aggregate({'quantity':['mean','std','count','sum']}) # groupby each 1 month
        
        df['Daily Average']=df['quantity']['sum']/30 
        a = df['quantity']['count']/30
        b = df['quantity']['std']*df['quantity']['std'] + df['quantity']['mean']*df['quantity']['mean']
        c = df['Daily Average']*df['Daily Average']
        d = a*b-c
        df['Standard deviation'] = d.transform(lambda x:x**0.5)
        df['Total demand'] = df['quantity']['sum']
        df['Frequency']    = df['quantity']['count']

        del df['quantity']
        df.columns = df.columns.droplevel(1)

        return render(request,'products/calculations.html',context={'df2':df.to_html(classes=('table table-striped')), 'error':error})

    else:
        error='<h3>No Data to Analyze</h3>' 
        df2 = None
        return render(request,'products/calculations.html',context={'df2':df2, 'error':error})


'''@login_required(login_url='login')
def sales_dist_view(request):
    graph = None
    error = None
    try:
        df = pd.DataFrame(Purchase.objects.filter(user=request.user).values())
        #df['user_id']=df['user_id'].apply(get_salesman_from_id)

products/templates/products/add.html
{% extends 'base.html'%}
{% load crispy_forms_tags %}

{% block title %} add purchase{% endblock title %}

{% block content %}
    <h1>Add</h1>
    <form action="" method="post">
        {% csrf_token %}
        {{ form|crispy }}
        <button type="submit" class="btn btn-primary">Submit</button>
    </form>
{% endblock %}

products/templates/products/add_inventory.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %} 
    <h1>Add Inventory</h1>
    <form action="" method="post">
        {% csrf_token %}
        {{ form|crispy }}
        <input type="submit" name="Submit">
    </form>
{% endblock %}

products/templates/products/add_items.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}
    <h1>Issue Item</h1>
    <form action="" method="post">
        {% csrf_token %}
        {{ form|crispy }}
        <input type="submit" name="Submit">
    </form>
{% endblock %}

products/templates/products/calculations.html
{% extends 'base.html' %}

{% block title  %} actual mean & variance {% endblock %}

{% block content  %}
    {% if df2 %}
        {{df2|safe}}
    {% endif %}
    {% if error %}
        {{error|safe}}
    {% endif %}
{% endblock %}

products/templates/products/delete_items.html
{% extends 'base.html' %}

{% block content %}
    <form action="" method="post">
        {% csrf_token %}
        <h1>Are you sure you want to delete.......... Item :  {{ item }}</h1><br>
        <input class="btn btn-danger" type="submit" value="Yes" />
        <a href="{% url 'products:items_list_url' %}"><div class="btn btn-primary">Cancel</div></a>
    </form>
{% endblock %}

products/templates/products/demand_create.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}
    <h1>Sales</h1>
    <br>
    <br>
    {% for message in messages %}
        <div class="alert alert-danger" role="alert">
          {{message}}
        </div>
    {%endfor%}
    <form method='POST' action=''>
        {% csrf_token %}
        {{form|crispy}}
        <input type="submit" class="btn btn-info" value='Create'/>
    </form>
{% endblock %}

products/templates/products/demand_list.html
{% extends 'base.html' %}

{% block title  %} Items List {% endblock %}

{% block content  %}
  <table class="table table-striped">
    <thead>
      <tr>
        <th scope="col">Name</th>
        <th scope="col">Price</th>
        <th scope="col">Quantity</th>
        <th scope="col">Time</th>
      </tr>
    </thead>
    
    {% for d in posts %}
    <tbody>
      <tr>
        <th scope="row">{{ d.product.name }}</th>
        <td>{{ d.price }}</td>
        <td>{{d.quantity}}</td>
        <td>{{d.date}}</td>
      </tr>
    </tbody>
    {% endfor %}
  </table>
  {% include "products/pagination.html" with page=posts %}
{% endblock %}

products/templates/products/item_create.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}
    <h1>Create Item</h1>
    {% if product_message %}
        <div class="ui success message">
            <i class="close icon"></i>
            <div class="header">{{ product_message }}</div>
        </div>
    {% endif %}
    <br>
    <br>
    {% for message in messages %}
        <div class="alert alert-danger" role="alert">
          {{message}}
        </div>
    {%endfor%}
    <form method='POST' action=''>
        {% csrf_token %}
        {{form|crispy}}
        <input type="submit" class="btn btn-info" value='Create'/>
    </form>
{% endblock %}

products/templates/products/items_list.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block title  %} Items List {% endblock %}

{% block content  %}

  {% for message in messages %}
    <div class="alert alert-danger" role="alert">
      {{message}}
    </div>
  {%endfor%}

  <form method='POST' action=''>
    {% csrf_token %}
    {{form|crispy}}
        <input type="submit" class="btn btn-info" value='Search'/>
  </form>

  <br>
    <a href="{% url 'products:items_list_url' %}" class="btn btn-primary btn-lg " role="button" >Show all Items</a>
    <a href="{% url 'products:item_create_url' %}" class="btn btn-secondary btn-lg "  role="button">Add new Item</a>

    <table class="table table-striped">
      <thead>
        <tr>
          <th scope="col">Name</th>
          <th scope="col">Inventory</th>
          <th scope="col">EOQ</th>
          <th scope="col">Reorder Quantity</th>
        </tr>
      </thead>

      {% for item in items %}
          <tbody>            
            {% if item.total_inventory <= item.rq %}
              <tr style="color: red;">
                <th scope="row">{{ item.name }}</th>
                <td>{{item.total_inventory}}</td>
                <td>{{item.eoq}}</td>
                <td>{{item.rq}}</td>
                <td><a href="{% url 'products:update_item' item.id %}" class="btn btn-outline-secondary" role="button">Update</a></td>
                <td><a href="{% url 'products:delete_items' item.id %}" class="btn btn-outline-danger" role="button">Delete</a></td>
              </tr>         
            {% endif %}
          </tbody>
      {% endfor %}

      {% for item in items %}
          <tbody>            
            {% if item.total_inventory > item.rq %}
              <tr>
                <th scope="row">{{ item.name }}</th>
                <td>{{item.total_inventory}}</td>
                <td>{{item.eoq}}</td>
                <td>{{item.rq}}</td>
                <td><a href="{% url 'products:update_item' item.id %}" class="btn btn-outline-secondary" role="button">Update</a></td>
                <td><a href="{% url 'products:delete_items' item.id %}" class="btn btn-outline-danger" role="button">Delete</a></td>
              </tr>         
            {% endif %}
          </tbody>
      {% endfor %}
    </table>

{% endblock %}

products/templates/products/main.html
{% extends 'base.html'%}

{% block title %}chart{% endblock title %} 

{% block content %} 
    <div>
        <div class="">

            {% if request.POST %}
                {% if graph %}
                    <img src="data:image/png;base64, {{ graph | safe}}">
                {% endif %}
            {% endif %}

        </div>
        <form action="" method="POST">
            {% csrf_token %}                
            <div class="card">
                <div class="card-header">Chart</div>
                <div class="card-body">  
                    <div class="form-group">
                        <label for="inputState">Choose a chart type:</label>
                        <select id="inputState" name="plot" class="form-control">
                            <option selected>---------</option>
                            <option value="bar">bar plot</option>
                            <option value="line">line plot</option>
                            <option value="count">count plot</option>
                        </select>
                    </div>

                    <div class="form-group">
                        <label>Raw material:</label><br>
                        <input type="text" name="item" class="col-md-10">
                    </div>

                    <div class="form-row">
                        <div class="form-group col-md-6">
                            <label>Date from:</label>
                            <input type="date" name="date_from">
                        </div>
                        <div class="form-group col-md-6">
                            <label>Date to:</label>
                            <input type="date" name="date_to">
                        </div>
                    </div>

                    <button type="submit" class="btn btn-primary">Submit</button>
                </div>
            </div><br>
                        
            {% if error_message %}          
                <div class="alert alert-warning alert-dismissible fade show" role="alert">
                    <strong>{{ error_message }}</strong>
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                    </button>
                </div>
            {% endif %}
        </form>
        <br>
        <div class="card">
            <div class="card-header">Raw materials</div>
            <div class="card-body"> 
                <div>
                    {% for a in items %}
                        {{a.name}}<br>
                    {% endfor %}
                </div>
            </div>
        </div><br>
    </div>
{% endblock content %}

products/templates/products/pagination.html
<div class="pagination">
    <span class="step-links">
        {% if page.has_previous %}
            <a href="?page={{ page.previous_page_number }}">Previous</a>
        {% endif %}
        <span class="current">
            Page {{ page.number }} of {{ page.paginator.num_pages }}.
        </span>
        {% if page.has_next %}
            <a href="?page={{ page.next_page_number }}">Next</a>
        {% endif %}
    </span>
</div>

products/templates/products/sales.html
{% extends 'base.html'%}

{% block title %}sales{% endblock title %}

{% block content %}

<u><h1>Sales</h1></u>
{% if graph %}
    <img src="data:image/png;base64, {{ graph | safe}}">
{% endif %} 

{% if error %}
    <h1>{{ error }}</h1>
{% endif %}

{% endblock content %}

products/templates/products/update_item.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}
    <h1>Update Item</h1>
    <br>
    <br>
    {% for message in messages %}
        <div class="alert alert-danger" role="alert">
          {{message}}
        </div>
    {%endfor%}
    <form method='POST' action=''>
        {% csrf_token %}
        {{form|crispy}}
        <input type="submit" class="btn btn-info" value='Create'/>
    </form>
{% endblock %}

products/templates/products/view.html
{% extends 'base.html' %}

{% block title %} View {% endblock %}

{% block content %}
    {% for td in user.todolist.all %}
	    <p>{{td.name}}</p>
    {% endfor %} 
{% endblock %}